name: Ghost Site - Build & Deploy on Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cs-ghost-imgae-build:
    name: CS Workflow
    uses: Coto-Studio/workflows/.github/workflows/ghost-image-build.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image-name: ghcr.io/coto-studio/ghost-beta-site
      stack-name: coto-studio

  cs-docker-stack-deploy:
    name: CS Workflow
    needs: cs-ghost-imgae-build
    uses: Coto-Studio/workflows/.github/workflows/docker-stack-deploy.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      vault-id: Coto.Studio - Clients
      item-id: mxq36tc4gvdzr34vv6otdqhzsy
      image-name: ghcr.io/coto-studio/ghost-beta-site
      stack-name: coto-studio
