name: Build & Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      vault-id:
        required: true
        type: string
      item-id:
        required: true
        type: string
      image-name:
        required: true
        type: string
      stack-name:
        required: true
        type: string
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

permissions:
  packages: write

jobs:
  cs-ghost-imgae-build:
    name: CS Workflow
    uses: Coto-Studio/workflows/.github/workflows/docker-build-image-v2.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  cs-docker-stack-deploy:
    name: CS Workflow
    needs: cs-ghost-imgae-build
    uses: Coto-Studio/workflows/.github/workflows/docker-stack-deploy-v2.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
