name: Ghost Site - Build & Deploy on Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cs-ghost-docker-deploy:
    name: CS Workflow
    uses: Coto-Studio/workflows/.github/workflows/ghost-image-build-and-deploy.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      vault-id: op://Coto.Studio - Clients
      item-id: mxq36tc4gvdzr34vv6otdqhzsy
      image-name: ghcr.io/coto-studio/ghost-s3
      stack-name: coto-studio
