name: Beta Site - Build & Deploy on Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-deploy:
    name: Ghost Site
    uses: ./.github/workflows/build-and-deploy.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
