name: Ghost Site - Build & Deploy on Schedule

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  check-base-image:
    name: CS Workflow
    uses: Coto-Studio/workflows/.github/workflows/check-base-image.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  # only execute subsequent steps if an update is actually NEEDED.
  build-and-deploy:
    name: Build & Deploy
    needs: check-base-image
    if: ${{ needs.check-base-image.outputs.rebuild }}
    uses: ./.github/workflows/build-and-deploy.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
