name: Ghost Site - Build & Deploy on Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-deploy:
    name: Ghost Site
    uses: ./.github/workflows/build-and-deploy.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      vault-id: Coto.Studio - Clients
      item-id: mxq36tc4gvdzr34vv6otdqhzsy
      image-name: ghcr.io/coto-studio/ghost-beta-site
      stack-name: coto-studio
